spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update

  cache:
    jcache:
      config: ehcache.xml

  jwt:
    secret: ${SPRING_JWT_SECRET}
    time: 360000

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}

  coolsms:
    api:
      key: ${SPRING_COOLSMS_API_KEY}
      secret: ${SPRING_COOLSMS_API_SECRET}
      domain: https://api.coolsms.co.kr
    from:
      phone-number: ${SPRING_COOLSMS_FROM_PHONE_NUMBER}
